{{- $rootPassword := randAlphaNum 42 }}
{{- $replicationPassword := randAlphaNum 42 }}
{{- $password := randAlphaNum 42 }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
    release: {{ .Release.Name }}
type: Opaque
data:
  mysql-root-password:  {{ .Values.mysql.auth.replicationPassword | default $rootPassword | b64enc}}
  mysql-replication-password:  {{ .Values.mysql.auth.replicationPassword | default $replicationPassword | b64enc}}
  mysql-username: {{ .Values.mysql.auth.username | default "kubeflow" | b64enc }}
  mysql-password: {{ .Values.mysql.auth.password | default  $password  | b64enc }}